added api name to config json file and added test for URL resolver
paypay/paypayopa-sdk-node pull request #128
Opened 2020-11-18 08:15 UTC by ashraf-km

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing](../blob/master/contributing.md) document?
* [ ] Have you read and signed the automated Contributor's License Agreement?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-11-18 08:36 UTC, solancer requested changes

2020-11-18 08:36 UTC, solancer commented on src/lib/httpsClient.ts
> +      // const RESOLVE_URL = `https://developer.paypay.ne.jp/develop/resolve?api_name=${}&code=${}&code_id=${}`
when there is an error it should print the console.log with the link.

code and code_id you will you get from the server response the API name you have to fetch from the conf method mapping

2020-11-22 10:36 UTC, shreyanshp reviewed
@solancer is this PR WIP or completed?

2020-11-22 10:36 UTC, shreyanshp commented on src/lib/httpsClient.ts
> +      // console.log(`This link should help you to troubleshoot the error: ${RESOLVE_URL}`)
Why is this commented out?

2020-11-23 12:27 UTC, solancer commented
Closing this PR since changes related to this was merged into master from PR #129

2020-11-23 12:27 UTC, closed without merging